---
- name: Install opentsdb
  yum: name={{ opentsdb_rpm_url }} state=present

- name: Configure opentsdb
  template:
    dest: /etc/opentsdb/opentsdb.conf
    src: opentsdb.conf.j2

- name: Create OpenTSDB tables
  shell: COMPRESSION=SNAPPY HBASE_HOME={{ hbase_home }} JAVA_HOME=/usr/java/latest {{ opentsdb_home }}/tools/create_table.sh
  when: opentsdb_create_tables

- name: Ensure opentsdb is running and enabled
  service: name=opentsdb state=restarted enabled=yes
